apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ekart-github-actions
  template:
    metadata:
      labels:
        app: ekart-github-actions
    spec:
      containers:
        - name: ekart
          image: suryasjv/ekart-app-github-actions:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070

---

apiVersion: v1
kind: Service
metadata:
  name: ekart-ssvc
spec:
  selector:
    app: ekart-github-actions
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
  type: NodePort
