apiVersion: v1
kind: Service
metadata:
  name: ekart-service
spec:
  selector:
    app: ekart-github-actions
  ports:
    - protocol: TCP
      port: 80          # Exposed on external IP
      targetPort: 8070  # App's container port
  type: LoadBalancer
