name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn compile
      
      - name: Build the app using Maven
        run: mvn clean install -DskipTests

      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ekart-app-gitHub-actions:latest
          file: docker/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build multi-platform Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/ekart-app-gitHub-actions:latest docker/Dockerfile


      - name: Deploy to Kubernetes (Kind Cluster)
        run: |
          kubectl apply -f deploymentservice.yml
          
      - name: Expose application and get URL
        run: |
          kubectl get svc ekart-app-service
